---
author: Xinran Miao
categories:
- Causal inference
date: "2022-10-27"
draft: false
excerpt: We demonstrate the identificability of natural mediation effects proved by [Imai, K., Keele, L. and Yamamoto, T.(2010)](https://doi.org/10.1214/10-STS321)
subtitle: 
title: Identifying Causal Mediation Effects
---
In this blog, we demonstrate the identificability of natural mediation effects proved in [Imai, K., Keele, L. and Yamamoto, T.(2010)](https://doi.org/10.1214/10-STS321). Please check this paper if you are interested!

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```




### Set-up
Consider a random sample of size $n$, where we observe $(X_i, T_i,M_i, Y_i)$ for each sample $i=1,\cdots,n$, where

> * $X_i$ : pretreatment covariate with support $\mathcal{X}$
> * $T_i$ : binary treatment variable,
> * $M_i$ : mediator variable with support $\mathcal{M}$,
> * $Y_i$ : outcome variable with support $\mathcal{Y}$.

In order to examine how treatment affect the outcome, we split the treatment effect into two parts depending on whether it works through the mediator. We control for measured confounders $X$.

For each sample $i$, we define its natural indirect effect 

$$\delta_i(t) = Y_i(t,M_i(1)) - Y_i(t,M_i(0))$$
and natural direct effect.

$$\zeta_i(t) = Y_i(1,M_i(t) - Y_i(0,M_i(t)).$$

Our interest are the average natural indirect effect

\begin{equation} 
  \bar\delta(t) = \mathbb{E}[Y_i(t,M_i(1)) - Y_i(t,M_i(0))]
  (\#eq:defin)
\end{equation} 



and the average natural direct effect 
\begin{equation} 
  \bar\zeta(t) = \mathbb{E}[Y(1, M(t)) - Y(0, M(t))]
  (\#eq:defdi)
\end{equation} 

with $t=0,1$. 




         

### Assumptions

For $t,t'=0,1$ and any $x\in\mathcal{X}$, we assume

\begin{equation} 
  \{Y_i(t',m), M_i(t)\}\perp T_i\mid X_i=x
  (\#eq:seq1)
\end{equation} 

\begin{equation}
 Y_i(t'm) \perp M_i(t)\mid T_i=t, X_i=x
   (\#eq:seq2)
\end{equation}

\begin{equation}
\text{Pr}(T_i=t\mid X_i=x)>0, \mathbb{P}(M_i(t)=m\mid T_i=t,X_i=x)>0
   (\#eq:positivity)
\end{equation}








### Identifiability
::: {.theorem}
${}$
Under the above sequential ignorability assumption, the average natural direct and indirect effects can be identifed as follows for $t=0,1$.

$$\bar\delta(t) = \iint\mathbb{E}(Y_i\mid M_i=m, T_i=t,X_i=x)\{dF_{M_i\mid T_i=1,X_i=x}(m) - dF_{M|i\mid T_1=0,X_i=x}(m)\}dF_{X_i}(x)$$

$$\bar\zeta(t) = \iint\{\mathbb{E}(Y_i\mid M_i=m,T_i=1,X_i=x)-\mathbb{E}(Y_i\mid M_i=m,T_i=0,X_i=x)\}dF_{M_i\mid T_i=t,X_i=x}(m)dF_{X_i}(x),$$
where $F_Z(\cdot)$ and $F_{X\mid W}(\cdot)$ represent the distribution function of a random variable $Z$ and the conditional ditribution function of $Z$ given $W$.
\hspace{12.5cm} 
:::



::: {.proof}
${}$
Notice that the sequential ignorability assumption implies



\begin{equation} 
  Y_i(t',m)\perp T_i\mid M_i(t)=m', X_i=x
  (\#eq:cond)
\end{equation} 



For any $t,t'=0,1$, we have 
\begin{align*}
\mathbb{E}(Y_i(t, M_i(t'))\mid X_i=x) &= \int\mathbb{E}(Y_i(t,m)\mid M_i(t')=m, X_i=x)dF_{M_i(t')\mid X_i=x}(m) \\
&=\int \mathbb{E}(Y_i(t,m)\mid M_i(t')=m,T_i=t',X_i=x)dF_{M_i(t')\mid X_i=x}(m)\\
&= \int\mathbb{E}(Y_i(t,m)\mid T_i=t', X_i=x)dF_{M_i(t')\mid X_i=x}(m)\\
&=\int\mathbb{E}(Y_i(t,m)\mid T_i=t, X_i=x)dF_{M_i(t')\mid T_i=t',X_i=x}(m)\\
&=\int\mathbb{E}(Y_i(t,m)\mid M_i(t)=m,T_i=t,X_i=x)dF_{M_i(t')\mid T_i=t',X_i=x}(m)\\
&=\int \mathbb{E}(Y_i\mid M_i=m, T_i=t, X_i=x)dF_{M_i(t')\mid T_i=t',X_i=x}(m)\\
&=\int\mathbb{E}(Y_i\mid M_i=m, T_i=t,X_i=x)dF_{M_i\mid T_i=t',X_i=x}(m),
\end{align*}
where the second equality follows from \@ref(eq:cond), the third and fifth equalities follow from \@ref(eq:seq1), the fourth and last equalities follow from \@ref(eq:seq2), and the sixth equality follows from the fact that $M_i=M_i(T_i)$ and $Y_i=Y_i(T_i, M_i(T_i))$.

Therefore, we have 
\begin{align*}
\mathbb{E}(Y_i(t,M_i(t')))=\iint \mathbb{E}(Y_i\mid M_i=m,T_i=t,X_i=x)dF_{M_i\mid T_i=t',X_i=x}(m)dF_{X_i}(x)
\end{align*}
Identifiability follows by plugging in the definition of average natural indirect and direct effects defined in \@ref(eq:defin) and \@ref(eq:defdi).
$\hspace{12.5cm} \square$
:::


### Reference

[A general approach to causal mediation analysis](https://doi.org/10.1037/a0020761)

[Identification, Inference and Sensitivity Analysis for Causal Mediation Effects](https://doi.org/10.1214/10-STS321)
